### ISSUE TITLE
Command  /timeset

### ISSUE THREAD

**Issue by ghost** [Ambiotic/Ambiotic#32]
Using the vanilla command /timeset to, say, return to time 0, does not cause the soundscape to change; i.e. it gets stuck on the soundscape of the time and place you were at at the time you used the command.

**Comment by jimcarreer** [comment]
How long did you wait?  So if it just turned to night and I time set it to 0, then yes, the night crickets still play for about a minute, but then it switches to day sounds.  The reason for this is I only update this engine World Time variable once every 50 ticks or so, since it (normally) doesn't change from one vaule to another quickly.  When you say its "stuck" does it eventually start working right or never?

**Comment by jimcarreer** [comment]
@Tetrajak : do you know how to use IRC?  You're a very good tester but I think we could possibly figure out these issues faster using real time chat.  I hang out in #minecraftforge on EsperNet as GraphicH.  Hit me up there and we can potentially work through these bugs more quickly. I use https://hexchat.github.io/ for IRC.
